server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: root
    url: jdbc:mongodb://localhost:27017/registration
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
    show-sql: true

