server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/registration
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
    show-sql: true

