server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: root
    url: jdbc:mongodb://localhost:27017/registration
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
    show-sql: true

application:
  jwt:
    secretKey: ASDnasdlkjaboi8e13jkAKLJSHDkl132lJASFAbsfkl4
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 14

allowed:
  origin: http://localhost:3000
